# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T02_Red_Team' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for T02_Red_Team
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
